/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppRoundsRouteImport } from './routes/_app/rounds'
import { Route as AppProductsRouteImport } from './routes/_app/products'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCustomersRouteImport } from './routes/_app/customers'
import { Route as AppRoundsIndexRouteImport } from './routes/_app/rounds/index'
import { Route as AppProductsIndexRouteImport } from './routes/_app/products/index'
import { Route as AppDashboardIndexRouteImport } from './routes/_app/dashboard/index'
import { Route as AppCustomersIndexRouteImport } from './routes/_app/customers/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppRoundsNewRouteImport } from './routes/_app/rounds/new'
import { Route as AppRoundsRoundIdRouteImport } from './routes/_app/rounds/$roundId'
import { Route as AppProductsProductIdRouteImport } from './routes/_app/products/$productId'
import { Route as AppDashboardAuditRouteImport } from './routes/_app/dashboard/audit'
import { Route as AppCustomersCustomerIdRouteImport } from './routes/_app/customers/$customerId'
import { Route as AppRoundsRoundIdIndexRouteImport } from './routes/_app/rounds/$roundId/index'
import { Route as ApiExportsKerryRoundIdRouteImport } from './routes/api/exports/kerry.$roundId'
import { Route as ApiExportsJapan05RoundIdRouteImport } from './routes/api/exports/japan05.$roundId'
import { Route as AppRoundsRoundIdSummaryRouteImport } from './routes/_app/rounds/$roundId/summary'
import { Route as AppRoundsRoundIdStatsRouteImport } from './routes/_app/rounds/$roundId/stats'
import { Route as AppRoundsRoundIdShippingRouteImport } from './routes/_app/rounds/$roundId/shipping'
import { Route as AppRoundsRoundIdPurchaseRouteImport } from './routes/_app/rounds/$roundId/purchase'
import { Route as AppRoundsRoundIdProductsRouteImport } from './routes/_app/rounds/$roundId/products'
import { Route as AppRoundsRoundIdOrdersRouteImport } from './routes/_app/rounds/$roundId/orders'
import { Route as AppDashboardRoundRoundIdRouteImport } from './routes/_app/dashboard/round/$roundId'
import { Route as AppRoundsRoundIdOrdersIndexRouteImport } from './routes/_app/rounds/$roundId/orders/index'
import { Route as AppRoundsRoundIdOrdersNewRouteImport } from './routes/_app/rounds/$roundId/orders/new'
import { Route as AppRoundsRoundIdOrdersOrderIdRouteImport } from './routes/_app/rounds/$roundId/orders/$orderId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRoundsRoute = AppRoundsRouteImport.update({
  id: '/rounds',
  path: '/rounds',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppRoundsIndexRoute = AppRoundsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoundsRoute,
} as any)
const AppProductsIndexRoute = AppProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProductsRoute,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppCustomersIndexRoute = AppCustomersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCustomersRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoundsNewRoute = AppRoundsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppRoundsRoute,
} as any)
const AppRoundsRoundIdRoute = AppRoundsRoundIdRouteImport.update({
  id: '/$roundId',
  path: '/$roundId',
  getParentRoute: () => AppRoundsRoute,
} as any)
const AppProductsProductIdRoute = AppProductsProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => AppProductsRoute,
} as any)
const AppDashboardAuditRoute = AppDashboardAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppCustomersCustomerIdRoute = AppCustomersCustomerIdRouteImport.update({
  id: '/$customerId',
  path: '/$customerId',
  getParentRoute: () => AppCustomersRoute,
} as any)
const AppRoundsRoundIdIndexRoute = AppRoundsRoundIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoundsRoundIdRoute,
} as any)
const ApiExportsKerryRoundIdRoute = ApiExportsKerryRoundIdRouteImport.update({
  id: '/api/exports/kerry/$roundId',
  path: '/api/exports/kerry/$roundId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExportsJapan05RoundIdRoute =
  ApiExportsJapan05RoundIdRouteImport.update({
    id: '/api/exports/japan05/$roundId',
    path: '/api/exports/japan05/$roundId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppRoundsRoundIdSummaryRoute = AppRoundsRoundIdSummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => AppRoundsRoundIdRoute,
} as any)
const AppRoundsRoundIdStatsRoute = AppRoundsRoundIdStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AppRoundsRoundIdRoute,
} as any)
const AppRoundsRoundIdShippingRoute =
  AppRoundsRoundIdShippingRouteImport.update({
    id: '/shipping',
    path: '/shipping',
    getParentRoute: () => AppRoundsRoundIdRoute,
  } as any)
const AppRoundsRoundIdPurchaseRoute =
  AppRoundsRoundIdPurchaseRouteImport.update({
    id: '/purchase',
    path: '/purchase',
    getParentRoute: () => AppRoundsRoundIdRoute,
  } as any)
const AppRoundsRoundIdProductsRoute =
  AppRoundsRoundIdProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AppRoundsRoundIdRoute,
  } as any)
const AppRoundsRoundIdOrdersRoute = AppRoundsRoundIdOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppRoundsRoundIdRoute,
} as any)
const AppDashboardRoundRoundIdRoute =
  AppDashboardRoundRoundIdRouteImport.update({
    id: '/round/$roundId',
    path: '/round/$roundId',
    getParentRoute: () => AppDashboardRoute,
  } as any)
const AppRoundsRoundIdOrdersIndexRoute =
  AppRoundsRoundIdOrdersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppRoundsRoundIdOrdersRoute,
  } as any)
const AppRoundsRoundIdOrdersNewRoute =
  AppRoundsRoundIdOrdersNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AppRoundsRoundIdOrdersRoute,
  } as any)
const AppRoundsRoundIdOrdersOrderIdRoute =
  AppRoundsRoundIdOrdersOrderIdRouteImport.update({
    id: '/$orderId',
    path: '/$orderId',
    getParentRoute: () => AppRoundsRoundIdOrdersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/customers': typeof AppCustomersRouteWithChildren
  '/dashboard': typeof AppDashboardRouteWithChildren
  '/products': typeof AppProductsRouteWithChildren
  '/rounds': typeof AppRoundsRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/customers/$customerId': typeof AppCustomersCustomerIdRoute
  '/dashboard/audit': typeof AppDashboardAuditRoute
  '/products/$productId': typeof AppProductsProductIdRoute
  '/rounds/$roundId': typeof AppRoundsRoundIdRouteWithChildren
  '/rounds/new': typeof AppRoundsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/customers/': typeof AppCustomersIndexRoute
  '/dashboard/': typeof AppDashboardIndexRoute
  '/products/': typeof AppProductsIndexRoute
  '/rounds/': typeof AppRoundsIndexRoute
  '/dashboard/round/$roundId': typeof AppDashboardRoundRoundIdRoute
  '/rounds/$roundId/orders': typeof AppRoundsRoundIdOrdersRouteWithChildren
  '/rounds/$roundId/products': typeof AppRoundsRoundIdProductsRoute
  '/rounds/$roundId/purchase': typeof AppRoundsRoundIdPurchaseRoute
  '/rounds/$roundId/shipping': typeof AppRoundsRoundIdShippingRoute
  '/rounds/$roundId/stats': typeof AppRoundsRoundIdStatsRoute
  '/rounds/$roundId/summary': typeof AppRoundsRoundIdSummaryRoute
  '/api/exports/japan05/$roundId': typeof ApiExportsJapan05RoundIdRoute
  '/api/exports/kerry/$roundId': typeof ApiExportsKerryRoundIdRoute
  '/rounds/$roundId/': typeof AppRoundsRoundIdIndexRoute
  '/rounds/$roundId/orders/$orderId': typeof AppRoundsRoundIdOrdersOrderIdRoute
  '/rounds/$roundId/orders/new': typeof AppRoundsRoundIdOrdersNewRoute
  '/rounds/$roundId/orders/': typeof AppRoundsRoundIdOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/settings': typeof AppSettingsRoute
  '/': typeof AppIndexRoute
  '/customers/$customerId': typeof AppCustomersCustomerIdRoute
  '/dashboard/audit': typeof AppDashboardAuditRoute
  '/products/$productId': typeof AppProductsProductIdRoute
  '/rounds/new': typeof AppRoundsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/customers': typeof AppCustomersIndexRoute
  '/dashboard': typeof AppDashboardIndexRoute
  '/products': typeof AppProductsIndexRoute
  '/rounds': typeof AppRoundsIndexRoute
  '/dashboard/round/$roundId': typeof AppDashboardRoundRoundIdRoute
  '/rounds/$roundId/products': typeof AppRoundsRoundIdProductsRoute
  '/rounds/$roundId/purchase': typeof AppRoundsRoundIdPurchaseRoute
  '/rounds/$roundId/shipping': typeof AppRoundsRoundIdShippingRoute
  '/rounds/$roundId/stats': typeof AppRoundsRoundIdStatsRoute
  '/rounds/$roundId/summary': typeof AppRoundsRoundIdSummaryRoute
  '/api/exports/japan05/$roundId': typeof ApiExportsJapan05RoundIdRoute
  '/api/exports/kerry/$roundId': typeof ApiExportsKerryRoundIdRoute
  '/rounds/$roundId': typeof AppRoundsRoundIdIndexRoute
  '/rounds/$roundId/orders/$orderId': typeof AppRoundsRoundIdOrdersOrderIdRoute
  '/rounds/$roundId/orders/new': typeof AppRoundsRoundIdOrdersNewRoute
  '/rounds/$roundId/orders': typeof AppRoundsRoundIdOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/customers': typeof AppCustomersRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRouteWithChildren
  '/_app/products': typeof AppProductsRouteWithChildren
  '/_app/rounds': typeof AppRoundsRouteWithChildren
  '/_app/settings': typeof AppSettingsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/customers/$customerId': typeof AppCustomersCustomerIdRoute
  '/_app/dashboard/audit': typeof AppDashboardAuditRoute
  '/_app/products/$productId': typeof AppProductsProductIdRoute
  '/_app/rounds/$roundId': typeof AppRoundsRoundIdRouteWithChildren
  '/_app/rounds/new': typeof AppRoundsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/customers/': typeof AppCustomersIndexRoute
  '/_app/dashboard/': typeof AppDashboardIndexRoute
  '/_app/products/': typeof AppProductsIndexRoute
  '/_app/rounds/': typeof AppRoundsIndexRoute
  '/_app/dashboard/round/$roundId': typeof AppDashboardRoundRoundIdRoute
  '/_app/rounds/$roundId/orders': typeof AppRoundsRoundIdOrdersRouteWithChildren
  '/_app/rounds/$roundId/products': typeof AppRoundsRoundIdProductsRoute
  '/_app/rounds/$roundId/purchase': typeof AppRoundsRoundIdPurchaseRoute
  '/_app/rounds/$roundId/shipping': typeof AppRoundsRoundIdShippingRoute
  '/_app/rounds/$roundId/stats': typeof AppRoundsRoundIdStatsRoute
  '/_app/rounds/$roundId/summary': typeof AppRoundsRoundIdSummaryRoute
  '/api/exports/japan05/$roundId': typeof ApiExportsJapan05RoundIdRoute
  '/api/exports/kerry/$roundId': typeof ApiExportsKerryRoundIdRoute
  '/_app/rounds/$roundId/': typeof AppRoundsRoundIdIndexRoute
  '/_app/rounds/$roundId/orders/$orderId': typeof AppRoundsRoundIdOrdersOrderIdRoute
  '/_app/rounds/$roundId/orders/new': typeof AppRoundsRoundIdOrdersNewRoute
  '/_app/rounds/$roundId/orders/': typeof AppRoundsRoundIdOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/customers'
    | '/dashboard'
    | '/products'
    | '/rounds'
    | '/settings'
    | '/customers/$customerId'
    | '/dashboard/audit'
    | '/products/$productId'
    | '/rounds/$roundId'
    | '/rounds/new'
    | '/api/auth/$'
    | '/customers/'
    | '/dashboard/'
    | '/products/'
    | '/rounds/'
    | '/dashboard/round/$roundId'
    | '/rounds/$roundId/orders'
    | '/rounds/$roundId/products'
    | '/rounds/$roundId/purchase'
    | '/rounds/$roundId/shipping'
    | '/rounds/$roundId/stats'
    | '/rounds/$roundId/summary'
    | '/api/exports/japan05/$roundId'
    | '/api/exports/kerry/$roundId'
    | '/rounds/$roundId/'
    | '/rounds/$roundId/orders/$orderId'
    | '/rounds/$roundId/orders/new'
    | '/rounds/$roundId/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/settings'
    | '/'
    | '/customers/$customerId'
    | '/dashboard/audit'
    | '/products/$productId'
    | '/rounds/new'
    | '/api/auth/$'
    | '/customers'
    | '/dashboard'
    | '/products'
    | '/rounds'
    | '/dashboard/round/$roundId'
    | '/rounds/$roundId/products'
    | '/rounds/$roundId/purchase'
    | '/rounds/$roundId/shipping'
    | '/rounds/$roundId/stats'
    | '/rounds/$roundId/summary'
    | '/api/exports/japan05/$roundId'
    | '/api/exports/kerry/$roundId'
    | '/rounds/$roundId'
    | '/rounds/$roundId/orders/$orderId'
    | '/rounds/$roundId/orders/new'
    | '/rounds/$roundId/orders'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/customers'
    | '/_app/dashboard'
    | '/_app/products'
    | '/_app/rounds'
    | '/_app/settings'
    | '/_app/'
    | '/_app/customers/$customerId'
    | '/_app/dashboard/audit'
    | '/_app/products/$productId'
    | '/_app/rounds/$roundId'
    | '/_app/rounds/new'
    | '/api/auth/$'
    | '/_app/customers/'
    | '/_app/dashboard/'
    | '/_app/products/'
    | '/_app/rounds/'
    | '/_app/dashboard/round/$roundId'
    | '/_app/rounds/$roundId/orders'
    | '/_app/rounds/$roundId/products'
    | '/_app/rounds/$roundId/purchase'
    | '/_app/rounds/$roundId/shipping'
    | '/_app/rounds/$roundId/stats'
    | '/_app/rounds/$roundId/summary'
    | '/api/exports/japan05/$roundId'
    | '/api/exports/kerry/$roundId'
    | '/_app/rounds/$roundId/'
    | '/_app/rounds/$roundId/orders/$orderId'
    | '/_app/rounds/$roundId/orders/new'
    | '/_app/rounds/$roundId/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiExportsJapan05RoundIdRoute: typeof ApiExportsJapan05RoundIdRoute
  ApiExportsKerryRoundIdRoute: typeof ApiExportsKerryRoundIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rounds': {
      id: '/_app/rounds'
      path: '/rounds'
      fullPath: '/rounds'
      preLoaderRoute: typeof AppRoundsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products': {
      id: '/_app/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers': {
      id: '/_app/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rounds/': {
      id: '/_app/rounds/'
      path: '/'
      fullPath: '/rounds/'
      preLoaderRoute: typeof AppRoundsIndexRouteImport
      parentRoute: typeof AppRoundsRoute
    }
    '/_app/products/': {
      id: '/_app/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof AppProductsIndexRouteImport
      parentRoute: typeof AppProductsRoute
    }
    '/_app/dashboard/': {
      id: '/_app/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/_app/customers/': {
      id: '/_app/customers/'
      path: '/'
      fullPath: '/customers/'
      preLoaderRoute: typeof AppCustomersIndexRouteImport
      parentRoute: typeof AppCustomersRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/rounds/new': {
      id: '/_app/rounds/new'
      path: '/new'
      fullPath: '/rounds/new'
      preLoaderRoute: typeof AppRoundsNewRouteImport
      parentRoute: typeof AppRoundsRoute
    }
    '/_app/rounds/$roundId': {
      id: '/_app/rounds/$roundId'
      path: '/$roundId'
      fullPath: '/rounds/$roundId'
      preLoaderRoute: typeof AppRoundsRoundIdRouteImport
      parentRoute: typeof AppRoundsRoute
    }
    '/_app/products/$productId': {
      id: '/_app/products/$productId'
      path: '/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof AppProductsProductIdRouteImport
      parentRoute: typeof AppProductsRoute
    }
    '/_app/dashboard/audit': {
      id: '/_app/dashboard/audit'
      path: '/audit'
      fullPath: '/dashboard/audit'
      preLoaderRoute: typeof AppDashboardAuditRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/_app/customers/$customerId': {
      id: '/_app/customers/$customerId'
      path: '/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof AppCustomersCustomerIdRouteImport
      parentRoute: typeof AppCustomersRoute
    }
    '/_app/rounds/$roundId/': {
      id: '/_app/rounds/$roundId/'
      path: '/'
      fullPath: '/rounds/$roundId/'
      preLoaderRoute: typeof AppRoundsRoundIdIndexRouteImport
      parentRoute: typeof AppRoundsRoundIdRoute
    }
    '/api/exports/kerry/$roundId': {
      id: '/api/exports/kerry/$roundId'
      path: '/api/exports/kerry/$roundId'
      fullPath: '/api/exports/kerry/$roundId'
      preLoaderRoute: typeof ApiExportsKerryRoundIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/exports/japan05/$roundId': {
      id: '/api/exports/japan05/$roundId'
      path: '/api/exports/japan05/$roundId'
      fullPath: '/api/exports/japan05/$roundId'
      preLoaderRoute: typeof ApiExportsJapan05RoundIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/rounds/$roundId/summary': {
      id: '/_app/rounds/$roundId/summary'
      path: '/summary'
      fullPath: '/rounds/$roundId/summary'
      preLoaderRoute: typeof AppRoundsRoundIdSummaryRouteImport
      parentRoute: typeof AppRoundsRoundIdRoute
    }
    '/_app/rounds/$roundId/stats': {
      id: '/_app/rounds/$roundId/stats'
      path: '/stats'
      fullPath: '/rounds/$roundId/stats'
      preLoaderRoute: typeof AppRoundsRoundIdStatsRouteImport
      parentRoute: typeof AppRoundsRoundIdRoute
    }
    '/_app/rounds/$roundId/shipping': {
      id: '/_app/rounds/$roundId/shipping'
      path: '/shipping'
      fullPath: '/rounds/$roundId/shipping'
      preLoaderRoute: typeof AppRoundsRoundIdShippingRouteImport
      parentRoute: typeof AppRoundsRoundIdRoute
    }
    '/_app/rounds/$roundId/purchase': {
      id: '/_app/rounds/$roundId/purchase'
      path: '/purchase'
      fullPath: '/rounds/$roundId/purchase'
      preLoaderRoute: typeof AppRoundsRoundIdPurchaseRouteImport
      parentRoute: typeof AppRoundsRoundIdRoute
    }
    '/_app/rounds/$roundId/products': {
      id: '/_app/rounds/$roundId/products'
      path: '/products'
      fullPath: '/rounds/$roundId/products'
      preLoaderRoute: typeof AppRoundsRoundIdProductsRouteImport
      parentRoute: typeof AppRoundsRoundIdRoute
    }
    '/_app/rounds/$roundId/orders': {
      id: '/_app/rounds/$roundId/orders'
      path: '/orders'
      fullPath: '/rounds/$roundId/orders'
      preLoaderRoute: typeof AppRoundsRoundIdOrdersRouteImport
      parentRoute: typeof AppRoundsRoundIdRoute
    }
    '/_app/dashboard/round/$roundId': {
      id: '/_app/dashboard/round/$roundId'
      path: '/round/$roundId'
      fullPath: '/dashboard/round/$roundId'
      preLoaderRoute: typeof AppDashboardRoundRoundIdRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/_app/rounds/$roundId/orders/': {
      id: '/_app/rounds/$roundId/orders/'
      path: '/'
      fullPath: '/rounds/$roundId/orders/'
      preLoaderRoute: typeof AppRoundsRoundIdOrdersIndexRouteImport
      parentRoute: typeof AppRoundsRoundIdOrdersRoute
    }
    '/_app/rounds/$roundId/orders/new': {
      id: '/_app/rounds/$roundId/orders/new'
      path: '/new'
      fullPath: '/rounds/$roundId/orders/new'
      preLoaderRoute: typeof AppRoundsRoundIdOrdersNewRouteImport
      parentRoute: typeof AppRoundsRoundIdOrdersRoute
    }
    '/_app/rounds/$roundId/orders/$orderId': {
      id: '/_app/rounds/$roundId/orders/$orderId'
      path: '/$orderId'
      fullPath: '/rounds/$roundId/orders/$orderId'
      preLoaderRoute: typeof AppRoundsRoundIdOrdersOrderIdRouteImport
      parentRoute: typeof AppRoundsRoundIdOrdersRoute
    }
  }
}

interface AppCustomersRouteChildren {
  AppCustomersCustomerIdRoute: typeof AppCustomersCustomerIdRoute
  AppCustomersIndexRoute: typeof AppCustomersIndexRoute
}

const AppCustomersRouteChildren: AppCustomersRouteChildren = {
  AppCustomersCustomerIdRoute: AppCustomersCustomerIdRoute,
  AppCustomersIndexRoute: AppCustomersIndexRoute,
}

const AppCustomersRouteWithChildren = AppCustomersRoute._addFileChildren(
  AppCustomersRouteChildren,
)

interface AppDashboardRouteChildren {
  AppDashboardAuditRoute: typeof AppDashboardAuditRoute
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
  AppDashboardRoundRoundIdRoute: typeof AppDashboardRoundRoundIdRoute
}

const AppDashboardRouteChildren: AppDashboardRouteChildren = {
  AppDashboardAuditRoute: AppDashboardAuditRoute,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
  AppDashboardRoundRoundIdRoute: AppDashboardRoundRoundIdRoute,
}

const AppDashboardRouteWithChildren = AppDashboardRoute._addFileChildren(
  AppDashboardRouteChildren,
)

interface AppProductsRouteChildren {
  AppProductsProductIdRoute: typeof AppProductsProductIdRoute
  AppProductsIndexRoute: typeof AppProductsIndexRoute
}

const AppProductsRouteChildren: AppProductsRouteChildren = {
  AppProductsProductIdRoute: AppProductsProductIdRoute,
  AppProductsIndexRoute: AppProductsIndexRoute,
}

const AppProductsRouteWithChildren = AppProductsRoute._addFileChildren(
  AppProductsRouteChildren,
)

interface AppRoundsRoundIdOrdersRouteChildren {
  AppRoundsRoundIdOrdersOrderIdRoute: typeof AppRoundsRoundIdOrdersOrderIdRoute
  AppRoundsRoundIdOrdersNewRoute: typeof AppRoundsRoundIdOrdersNewRoute
  AppRoundsRoundIdOrdersIndexRoute: typeof AppRoundsRoundIdOrdersIndexRoute
}

const AppRoundsRoundIdOrdersRouteChildren: AppRoundsRoundIdOrdersRouteChildren =
  {
    AppRoundsRoundIdOrdersOrderIdRoute: AppRoundsRoundIdOrdersOrderIdRoute,
    AppRoundsRoundIdOrdersNewRoute: AppRoundsRoundIdOrdersNewRoute,
    AppRoundsRoundIdOrdersIndexRoute: AppRoundsRoundIdOrdersIndexRoute,
  }

const AppRoundsRoundIdOrdersRouteWithChildren =
  AppRoundsRoundIdOrdersRoute._addFileChildren(
    AppRoundsRoundIdOrdersRouteChildren,
  )

interface AppRoundsRoundIdRouteChildren {
  AppRoundsRoundIdOrdersRoute: typeof AppRoundsRoundIdOrdersRouteWithChildren
  AppRoundsRoundIdProductsRoute: typeof AppRoundsRoundIdProductsRoute
  AppRoundsRoundIdPurchaseRoute: typeof AppRoundsRoundIdPurchaseRoute
  AppRoundsRoundIdShippingRoute: typeof AppRoundsRoundIdShippingRoute
  AppRoundsRoundIdStatsRoute: typeof AppRoundsRoundIdStatsRoute
  AppRoundsRoundIdSummaryRoute: typeof AppRoundsRoundIdSummaryRoute
  AppRoundsRoundIdIndexRoute: typeof AppRoundsRoundIdIndexRoute
}

const AppRoundsRoundIdRouteChildren: AppRoundsRoundIdRouteChildren = {
  AppRoundsRoundIdOrdersRoute: AppRoundsRoundIdOrdersRouteWithChildren,
  AppRoundsRoundIdProductsRoute: AppRoundsRoundIdProductsRoute,
  AppRoundsRoundIdPurchaseRoute: AppRoundsRoundIdPurchaseRoute,
  AppRoundsRoundIdShippingRoute: AppRoundsRoundIdShippingRoute,
  AppRoundsRoundIdStatsRoute: AppRoundsRoundIdStatsRoute,
  AppRoundsRoundIdSummaryRoute: AppRoundsRoundIdSummaryRoute,
  AppRoundsRoundIdIndexRoute: AppRoundsRoundIdIndexRoute,
}

const AppRoundsRoundIdRouteWithChildren =
  AppRoundsRoundIdRoute._addFileChildren(AppRoundsRoundIdRouteChildren)

interface AppRoundsRouteChildren {
  AppRoundsRoundIdRoute: typeof AppRoundsRoundIdRouteWithChildren
  AppRoundsNewRoute: typeof AppRoundsNewRoute
  AppRoundsIndexRoute: typeof AppRoundsIndexRoute
}

const AppRoundsRouteChildren: AppRoundsRouteChildren = {
  AppRoundsRoundIdRoute: AppRoundsRoundIdRouteWithChildren,
  AppRoundsNewRoute: AppRoundsNewRoute,
  AppRoundsIndexRoute: AppRoundsIndexRoute,
}

const AppRoundsRouteWithChildren = AppRoundsRoute._addFileChildren(
  AppRoundsRouteChildren,
)

interface AppRouteChildren {
  AppCustomersRoute: typeof AppCustomersRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRouteWithChildren
  AppProductsRoute: typeof AppProductsRouteWithChildren
  AppRoundsRoute: typeof AppRoundsRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCustomersRoute: AppCustomersRouteWithChildren,
  AppDashboardRoute: AppDashboardRouteWithChildren,
  AppProductsRoute: AppProductsRouteWithChildren,
  AppRoundsRoute: AppRoundsRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiExportsJapan05RoundIdRoute: ApiExportsJapan05RoundIdRoute,
  ApiExportsKerryRoundIdRoute: ApiExportsKerryRoundIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
